
ALTER TABLE events ADD COLUMN IF NOT EXISTS slug VARCHAR(255) UNIQUE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS bath_name VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS bath_address VARCHAR(500);
ALTER TABLE events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS program TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS rules TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS price_amount INTEGER DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS price_label VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS total_spots INTEGER DEFAULT 10;
ALTER TABLE events ADD COLUMN IF NOT EXISTS spots_left INTEGER DEFAULT 10;
ALTER TABLE events ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;

CREATE TABLE IF NOT EXISTS event_signups (
    id SERIAL PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES events(id),
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    telegram VARCHAR(100),
    status VARCHAR(20) DEFAULT 'new',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_signups_event_id ON event_signups(event_id);
CREATE INDEX IF NOT EXISTS idx_events_slug ON events(slug);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
