
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    telegram VARCHAR(100),
    password_hash VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE event_signups ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE event_signups ADD COLUMN IF NOT EXISTS consent_pd BOOLEAN DEFAULT false;
ALTER TABLE event_signups ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);
