ALTER TABLE t_p99966623_warm_meetings_experi.users
ADD COLUMN IF NOT EXISTS notify_email BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notify_telegram BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notify_vk BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notify_sms BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tg_user_id BIGINT,
ADD COLUMN IF NOT EXISTS tg_chat_id BIGINT,
ADD COLUMN IF NOT EXISTS tg_notify_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE t_p99966623_warm_meetings_experi.notification_preferences
ADD COLUMN IF NOT EXISTS notify_booking BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notify_urgent BOOLEAN DEFAULT TRUE;
