export const EVENTS = [
  {
    id: 1,
    title: "Баня «У Лешего» — Мужской пар",
    type: "парение",
    typeIcon: "Flame",
    date: "Сб, 26 апр",
    time: "18:00",
    timeEnd: "23:00",
    place: "Баня «У Лешего»",
    city: "Москва",
    price: 2500,
    priceLabel: "2 500 ₽",
    spots: 10,
    spotsLeft: 3,
    featured: true,
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
    tags: ["Хамам", "Веники", "Чай"],
    rating: 4.9,
    reviews: 42,
    organizer: "Алексей П.",
    color: "from-orange-500 to-amber-400",
    typeColor: "bg-orange-100 text-orange-700",
  },
  {
    id: 2,
    title: "Баня + знакомства — Субботний вечер",
    type: "знакомство",
    typeIcon: "Users",
    date: "Сб, 3 мая",
    time: "19:00",
    timeEnd: "23:00",
    place: "Сандуны",
    city: "Москва",
    price: 3200,
    priceLabel: "3 200 ₽",
    spots: 12,
    spotsLeft: 7,
    featured: false,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=80",
    tags: ["Нетворкинг", "Банкет", "18+"],
    rating: 4.7,
    reviews: 28,
    organizer: "Мария С.",
    color: "from-blue-500 to-indigo-400",
    typeColor: "bg-blue-100 text-blue-700",
  },
  {
    id: 3,
    title: "Мастер-класс: веничный массаж",
    type: "мастер-класс",
    typeIcon: "GraduationCap",
    date: "Вс, 4 мая",
    time: "11:00",
    timeEnd: "14:00",
    place: "Баня на Пресне",
    city: "Москва",
    price: 4500,
    priceLabel: "4 500 ₽",
    spots: 6,
    spotsLeft: 1,
    featured: true,
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80",
    tags: ["Практика", "Сертификат"],
    rating: 5.0,
    reviews: 15,
    organizer: "Иван Т.",
    color: "from-violet-500 to-purple-400",
    typeColor: "bg-violet-100 text-violet-700",
  },
  {
    id: 4,
    title: "Женский ретрит — пар + медитация",
    type: "практика",
    typeIcon: "Sparkles",
    date: "Пт, 9 мая",
    time: "16:00",
    timeEnd: "21:00",
    place: "Варшавские бани",
    city: "Москва",
    price: 3800,
    priceLabel: "3 800 ₽",
    spots: 8,
    spotsLeft: 5,
    featured: false,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    tags: ["Женский", "Йога", "Дыхание"],
    rating: 4.8,
    reviews: 31,
    organizer: "Ольга В.",
    color: "from-pink-500 to-rose-400",
    typeColor: "bg-pink-100 text-pink-700",
  },
  {
    id: 5,
    title: "Зимняя баня + прорубь",
    type: "практика",
    typeIcon: "Snowflake",
    date: "Сб, 10 мая",
    time: "09:00",
    timeEnd: "13:00",
    place: "Высота 30",
    city: "Подмосковье",
    price: 2000,
    priceLabel: "2 000 ₽",
    spots: 15,
    spotsLeft: 0,
    featured: false,
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    tags: ["Экстрим", "Природа"],
    rating: 4.6,
    reviews: 19,
    organizer: "Дмитрий К.",
    color: "from-cyan-500 to-sky-400",
    typeColor: "bg-cyan-100 text-cyan-700",
  },
  {
    id: 6,
    title: "Пятничный пар — свидания в бане",
    type: "свидание",
    typeIcon: "Heart",
    date: "Пт, 16 мая",
    time: "19:00",
    timeEnd: "23:00",
    place: "Сандуны",
    city: "Москва",
    price: 5500,
    priceLabel: "5 500 ₽",
    spots: 10,
    spotsLeft: 4,
    featured: true,
    image: "https://images.unsplash.com/photo-1609183480405-cc2750872f09?w=800&q=80",
    tags: ["Пары", "Романтика", "Ужин"],
    rating: 4.9,
    reviews: 23,
    organizer: "Алексей П.",
    color: "from-rose-500 to-pink-400",
    typeColor: "bg-rose-100 text-rose-700",
  },
];

export const TYPES = ["Все", "парение", "знакомство", "мастер-класс", "практика", "свидание"];

export function spotsText(left: number, total: number) {
  if (left === 0) return { text: "Мест нет", cls: "text-red-600" };
  if (left <= 2) return { text: `Осталось ${left}`, cls: "text-orange-500" };
  return { text: `${left} из ${total}`, cls: "text-emerald-600" };
}

export function SpotsBar({ left, total }: { left: number; total: number }) {
  const pct = total > 0 ? Math.round(((total - left) / total) * 100) : 0;
  const color = left === 0 ? "bg-red-400" : left <= 2 ? "bg-orange-400" : "bg-emerald-400";
  return (
    <div className="h-1 rounded-full bg-black/10 overflow-hidden w-full">
      <div className={`h-full ${color} transition-all`} style={{ width: `${pct}%` }} />
    </div>
  );
}
